// Generated by Editor
import React from "react";
import { Navigation1 } from "../global-sections/page/home/production/navbar";
import { HeroSection1 } from "../global-sections/page/home/production/hero";
import { Footer1 } from "../mock/template/sections/footer";

export default function GeneratedPage() {
    return (
        <div className="w-full bg-white h-full relative">
            <div className="template-root flex flex-col min-h-screen">
                <Navigation1
                    logo={undefined}
                    navigationLinks={[
                        { id: "1", label: "الرئيسية", url: "/" },
                        { id: "2", label: "المنتجات", url: "/products" },
                        { id: "3", label: "تفاصيل المنتج", url: "/product/1" },
                        { id: "4", label: "تواصل معنا", url: "/contact" }
                    ]}
                    primaryColor="#4272FF"
                />
                <main className="flex-grow">
                    <HeroSection1
                        title="مرحباً بك في متجرنا"
                        description="اكتشف مجموعتنا المميزة من المنتجات"
                    />
                </main>

            </div>
        </div>
    );
}
