
// Map of component names to their import paths (Mock for server generator)
const COMPONENT_IMPORTS: Record<string, string> = {
    "Navigation1": "../global-sections/page/home/production/navbar",
    "HeroSection1": "../global-sections/page/home/production/hero",
    "HeroSection2": "../global-sections/page/home/production/hero",
    "HeroSection4": "../global-sections/page/home/production/hero",
    "HeroSection5": "../global-sections/page/home/production/hero",
    "HeroCarousel": "../global-sections/page/home/production/hero/hero-carousel",
    "Footer1": "../mock/template/sections/footer", // Mock path
    // Add other components as needed
};

export const generateCodeFromJSON = (json: any): string => {
    if (!json) return "// No JSON data provided";

    const imports = new Set<string>();
    const componentName = "GeneratedPage";

    const generateJSX = (node: any, indentLevel = 2): string => {
        if (!node) return "null";

        // Handle primitive types
        if (typeof node === "string") return `"${node}"`;
        if (typeof node === "number" || typeof node === "boolean") return String(node);

        // Handle arrays
        if (Array.isArray(node)) {
            // Return fragment for array at root level or list of elements
            return `
          <>
            ${node.map(child => generateJSX(child, indentLevel)).join('\n' + '  '.repeat(indentLevel))}
          </>
        `;
        }

        if (node.type) {
            if (COMPONENT_IMPORTS[node.type]) {
                imports.add(`import { ${node.type} } from "${COMPONENT_IMPORTS[node.type]}";`);
            } else if (node.type !== "div" && node.type !== "main" && node.type !== "header" && node.type !== "footer" && node.type !== "section" && !node.type.startsWith("html")) {
                // If it's a custom component but not in our map, we might comment it or add a generic import
                imports.add(`// import { ${node.type} } from "...";`);
            }

            const indent = "  ".repeat(indentLevel);
            const childIndent = "  ".repeat(indentLevel + 1);

            // Props processing
            const propsString = Object.entries(node.props || {})
                .filter(([key]) => key !== "children")
                .map(([key, value]) => {
                    if (value === undefined) return "";
                    if (typeof value === "string") return `${key}="${value}"`;
                    if (typeof value === "function") return ""; // Skip functions in code gen
                    if (typeof value === "object") return `${key}={${JSON.stringify(value)}}`;
                    // For boolean props
                    if (typeof value === "boolean") return value ? key : `${key}={false}`;
                    return `${key}={${value}}`;
                })
                .filter(s => s !== "")
                .join("\n" + indent + "  ");

            let childrenCode = "";
            if (node.children) {
                if (Array.isArray(node.children)) {
                    childrenCode = node.children
                        .map((child: any) => generateJSX(child, indentLevel + 1))
                        .join("\n" + childIndent);
                } else {
                    childrenCode = generateJSX(node.children, indentLevel + 1);
                }
            }

            const openTag = propsString
                ? `<${node.type}\n${indent}  ${propsString}\n${indent}>`
                : `<${node.type}>`;

            if (!childrenCode) {
                return propsString
                    ? `<${node.type}\n${indent}  ${propsString}\n${indent}/>`
                    : `<${node.type} />`;
            }

            return `${openTag}\n${childIndent}${childrenCode}\n${indent}</${node.type}>`;
        }

        return "null";
    };

    const jsxContent = generateJSX(json, 2);
    const importsStr = Array.from(imports).join("\n");

    return `// Generated by Editor
import React from "react";
${importsStr}

export default function ${componentName}() {
  return (
    <div className="w-full bg-white h-full relative">
      ${jsxContent.trim()}
    </div>
  );
}
`;
};
